version: "3.1"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: "docker/nginx/Dockerfile"
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
    working_dir: "/var/www/html"
    depends_on:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: "docker/php-fpm/Dockerfile"
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html"
    working_dir: "/var/www/html"
    networks:
      - internal
networks:
  internal:
    driver: "bridge"