version: "3.1"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: "docker/nginx/Dockerfile"
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
    working_dir: "/var/www/html"
    depends_on:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: "docker/php-fpm/Dockerfile"
    volumes:
      - ".:/var/www/html"
    working_dir: "/var/www/html"
    env_file:
      - .env
    networks:
      - internal

  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slim_setup
      MYSQL_USER: slim_setup
      MYSQL_PASSWORD: slim_setup
    networks:
      - internal
networks:
  internal:
    driver: "bridge"
